name: Deployment Workflow
on:
  push:
    branches: [Production]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh commands test
        uses: appleboy/ssh-action@master
        with:
          host: 141.144.254.88
          username: opc
          key: ${{ secrets.PRIV_SECRET }}
          port: 22
          script: |
            cd /home/git-test/hotfixes/
            git pull origin Production
